name: Trigger Build on PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        env:
          SANDBOX_APP_KEY: ${{ secrets.SFDC_PROD_CLIENTID }}
          SANDBOX_USERNAME: ${{ secrets.SFDC_PROD_USER }}
          SANDBOX_CERT_KEY: ${{ secrets.SFDC_SERVER_KEY }}
        run: |
          chmod +x ./build/*.sh
          ./build/install_dependencies.sh
          ./build/create-scratch-org-sandbox.sh "$SANDBOX_CERT_KEY" "$SANDBOX_APP_KEY" "$SANDBOX_USERNAME" 
          ./build/run_apex_tests.sh
        shell: bash